### ISSUE TITLE
Preparar la reunión con ANLA

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/bioregistros-app#1]
Preparar la reunión con la ANLA para definir los usuarios de la herramienta y presentar la idea general del producto.

**Comment by heleolaya** [comment]
La reunión ya se programó para le viernes 14 de agosto de 9:00 am a 10:30 am

**Comment by erikasv** [comment]
Conclusiones:

* Los usuarios objetivo son los empleados de la ANLA, de manera que no saben la codificación previa de los datos.
* Manual de usuario explicito (para dummies)
