### ISSUE TITLE
Probar script taxonómico

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/bioregistros-app#14]
Probar el script de Juan Carlos y buscar formas de integrarlo con el de la carga de datos.

**Comment by crcruzr** [comment]
Se revisó la opción generada por Juan y de esta se considera útil la validación del nombre de la especie. Es pertienente evaluar si sumamos también la taxonomía superior, dado que esta ya viene en las GDB. 

Se podría adicionalmente incluir en el Shinny una opción que permitacargar la lista de referencia, para que el proceso pueda dar dos contrastes: i) a nivel de BD internacionales y ii) con información a nivel local
