### ISSUE TITLE
Crear control para que el usuario pueda seleccionar el sistema de origen de las coordenadas

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/bioregistros-app#19]
El control debe ser una opción de selección múltiple, con un botón ("Transformar") que de inicio a la transformación de los datos (Conexión que se realiza en la tarea #20)

**Comment by crcruzr** [comment]
Se integró el control para que el usuario defina el sistema de coordenadas. Aun queda pendiente que el resultado este concatenado con las columnas que selecciona el usuario
