### ISSUE TITLE
Integrar funciones de transformación con el control de selección de sistema de coordenadas e inicio de trasformación

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/bioregistros-app#20]
- Escribir los errores de los registros en un archivo
- Mostrar un aviso con la información sobre los datos que seguirán en el proceso. (Avisar que solo continuarán los datos que están bien).

**Comment by crcruzr** [comment]
Se integraron las funciones:
- corr.geonames
- add.corr.dt
- trans.coord

De estas, las dos primeras funcionan de manera correcta, pero la tercera, a pesar que se ejecuta no reconoce la selección de columnas que se visualiza en el Shiny. Es por ello que se requiere revisar como hacer para que la selección que se realice para la tercer función, defina la respuesta obtenida.

Adicionalmente se incorporó opción de descarga para las dos pestañas generadas, de forma tal que el usuario pueda dar trazabilidad al proceso.
