### ISSUE TITLE
Crear interfaz gráfica para el modulo de BioModelos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/bioregistros-app#35]
La idea es tener la pestaña del módulo de BioModelos con los siguientes elementos:

* Un botón para subir el shape del polígono del proyecto
* Un botón para realizar la consulta de consulta
* El resultado de la consulta se visualizará en una tabla con las especies que se encuentran potencialmente dentro de ese polígono

En caso de tener dudas consultar con @elkalexno

**Comment by marcelo-villa-p** [comment]
@elkalexno :

1. ¿El shape del polígono se sube en un archivo comprimido (`.zip`) o el usuario debe poder seleccionar todos los archivos relevantes (`.shp`, `.prj`, etc...)?
2. ¿Hay un límite para el tamaño del shapefile? Shiny pone un máximo de 5MB por defecto pero este valor se puede cambiar.

**Comment by marcelo-villa-p** [comment]
@elkalexno @crcruzr 

Quedó la pestaña de BioModelos con:

- `fileInput` para cargar el Shapefile con el polígono (el id es `shapeBiomodelos`).
- `actionButton` para conectar la lógica de intersección que ustedes desarrollen (el id es `intersectBiomodelos`).
- `dataTableOutput` para conectar con el resultado (`dataframe`) de la lógica que ustedes desarrollen (el id es `tableBiomodelos`).
