### ISSUE TITLE
Implementar ajustes a los datos cargados a la herramienta

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/bioregistros-app#8]
Es necesario implementar la lógica para ajustar los siguientes puntos a partir de los datos:

- Selección del origen de los datos (origen de colección de datos).
- Verificación y estandarización de los campos mínimos obligatorios del SiB Colombia.
- Transformación del sistema de coordenadas de Latitud y Longitud 
- Transformación de los campos de departamentos y municipios
- Transformación del formato de fechas (si aplica)

**Comment by crcruzr** [comment]
Se crearon tres funciones para dar respuesta a los ajustes que se debian dar a los datos originales. Es pertienente tener en cuenta que para la trasformación de departamentos y municipios, existe un archivo adicional que contiene los ajustes que se deben realizar.
