### ISSUE TITLE
Ajustes a la interfaz para el proceso de carga de datos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/bioregistros-app#9]
Ajustar en la interfaz los siguientes controles como parte del proceso de carga de datos:

- Nota a la interfaz con respecto a la codificación de la GDB (sólo se garantizan resultados con UTF-8)
- Input para la selección del origen de los datos

**Comment by crcruzr** [comment]
a. En los ajustes se solucionó el problema que impedía limitar el número de registros en la interfaz
b. La visualicación presenta errores cuando se incluyen tíldes en las descripciones
